### ISSUE TITLE
Ошибка на iOS

### ISSUE THREAD

**Issue by EnOane** [Innim/my_target_flutter#5]
Привет, на ios использую свой блок INTERSTITIAL вылетает вот это 

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(ADS_NOT_FOUND, Ads with uid <1231853_6037800> not found, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      MyTargetFlutter._show (package:my_target_flutter/src/my_target_flutter.dart:63:5)
<asynchronous suspension>
#3      InterstitialAd.show (package:my_target_flutter/src/my_target_flutter.dart:95:5)
<asynchronous suspension>

**Comment by EnOane** [comment]
Нет ошибок, я тюлень
